"""empty message

Revision ID: 36675e609e42
Revises: 3d033b29d1f1
Create Date: 2026-05-23 03:24:26.634279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36675e609e42'
down_revision = '3d033b29d1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('registration_deadline', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('registration_deadline')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
