"""empty message

Revision ID: 69737a70cb1b
Revises: c93a2e33b6c6
Create Date: 2026-05-15 17:00:53.645855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69737a70cb1b'
down_revision = 'c93a2e33b6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscription')
    # ### end Alembic commands ###
