"""add peso and altura

Revision ID: 902c9a194c12
Revises: ffc656399e08
Create Date: 2026-05-29 19:56:44.108797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902c9a194c12'
down_revision = 'ffc656399e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('altura')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
