"""empty message

Revision ID: 960c1afece28
Revises: 69737a70cb1b
Create Date: 2026-05-15 17:09:06.961288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '960c1afece28'
down_revision = '69737a70cb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.alter_column('registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.alter_column('registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
