"""empty message

Revision ID: 9e0cd813d5f2
Revises: 108a8127ea90
Create Date: 2026-06-03 17:31:42.690578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0cd813d5f2'
down_revision = '108a8127ea90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('registration_deadline', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('altura')
        batch_op.drop_column('peso')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('registration_deadline')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
